# neanno config file for airline_tickets sample

# notes: - this file contains a few settings which have been commented out.
#          these comments are included intentionally to show what other
#          configuration options exist.
#        - categories, key_terms, named_entities, spacy, instructions nodes
#          are optional. if they are not specified, neanno will disable the
#          respective features.

dataset:
    source: csv:samples/airline_tickets/texts.annotating.csv
    text_column: text
    is_annotated_column: is_text_annotated
    target: csv:samples/airline_tickets/texts.annotating.csv

categories:
  definitions:
    - name: Trip Planning
    - name: Service Offering/Procedure
    - name: Technology
    - name: Mileage Plan
    - name: Security
    - name: Customs/Immigration
    - name: Legal
    - name: Complaint/Feedback
  column: categories
  predictors:
    # Random Categories
    - name: Random Categories
      module: neanno.prediction.categories.from_random
      class: FromRandomCategoryPredictor
      is_prediction_enabled: true

key_terms:
  #shortcuts:
  #  standalone: Alt+1
  #  parented: Alt+2
  #  backcolor: "#333333"
  #  forecolor: "#50e6ff"
  predictors:
    # Key Terms from Dataset
    - name: Key Terms from Dataset
      module: neanno.prediction.key_terms.from_dataset
      class: FromDatasetKeyTermsPredictor
      is_prediction_enabled: true
      location: csv:samples/airline_tickets/default.key_terms.csv
    # Key Terms from Regexes
    - name: Key Terms from Regexes
      module: neanno.prediction.key_terms.from_regexes
      class: FromRegexesKeyTermsPredictor
      is_prediction_enabled: true
      patterns:
        - name: terminals
          pattern: (?i)(\bterminal\s*\d+\b)|(\bT[1-9]\b)|(\bterminal\b)

named_entities:
  definitions:
      - code: FROM
        shortcut: Alt+F
        # maincolor: "#ff8c31"
        # backcolor: "#333333"
        # forecolor: "#ff8c31"
      - code: TO
        shortcut: Alt+T
      - code: VIA
        shortcut: Alt+V
      - code: AT
        shortcut: Alt+A
      - code: AIRLINE
        shortcut: Alt+L
      - code: AIRCRAFT
        shortcut: Alt+C
  predictors:
    # Named Entities from Dataset
    - name: Named Entities from Dataset
      module: neanno.prediction.named_entities.from_datasets
      class: FromDatasetsNamedEntitiesPredictor
      is_prediction_enabled: true
      datasets:
        - code: AIRLINE
          location: csv:samples/airline_tickets/airlines.named_entities.csv
        # - code: ...
    # Named Entities from Regexes
    - name: Named Entities from Regexes
      module: neanno.prediction.named_entities.from_regexes
      class: FromRegexesNamedEntitiesPredictor
      is_prediction_enabled: true
      patterns:
      - entity: FROM
        pattern: (?<=\bfrom\s)[A-Z][A-Za-z]+\b
        #parent_terms: just an example to show that we can add parent terms here as well
      - entity: TO
        pattern: (?<=\bto\s)[A-Z][A-Za-z]+\b
      - entity: VIA
        pattern: (?<=\bvia\s)[A-Z][A-Za-z]+\b
      - entity: AIRCRAFT
        pattern: (A\s*)?3[28]0|(B\s*)?7\d7(-\d{3})|(Boeing\s*)?7\d7(-\d{3})CRJ|MD-\d{2}?
      #- entity: TIME
      #  pattern: "(?x)
      #             January \\b | Jan \\b | February \\b | Feb \\b | March \\b | Mar \\b | April \\b | Apr \\b
      #            | May \\b | June \\b | Jun \\b | July \\b | Jul \\b | August \\b | Aug \\b | September \\b
      #            | Sep \\b | October \\b | Oct \\b | November \\b | Nov \\b | December \\b | Dec \\b
      #            | \\b(([01]?[0-9])|(2[0-3]))[:\\.]?[0-5][0-9]\\s*([Aa]\\.?[Mm]\\.?|[Pp]\\.?[Mm]\\.?|hrs)\\b
      #           "
    - name: Named Entities from spacy
      module: neanno.prediction.named_entities.from_spacy
      class: FromSpacyNamedEntitiesPredictor
      is_prediction_enabled: true
      source_model: blank:en
      target_model_directory: samples/airline_tickets/spacy_model
      target_model_name: airline_tickets

instructions: "
Put your instructions for the annotators here.
<br/>
You can even use <b>HTML</b>.
"